@ECHO OFF

CHCP 65001

SETLOCAL ENABLEDELAYEDEXPANSION

SET DST=%2

@ECHO "@DLL_VARIABLE@->#define ICONV_CONST const%%~aextern"
SET SRC=%1
SET OLD=extern @DLL_VARIABLE@
SET NEW=!#define ICONV_CONST const^

extern!
FOR /F "TOKENS=*" %%S IN (%SRC%) DO (
	SET TMP=%%S
	IF NOT !TMP!.==. (
	  SET TMP=!TMP:%OLD%=#define ICONV_CONST const^

extern!
	  @ECHO !TMP!>>TMP.TMP
	)
)
MOVE TMP.TMP %DST%

@ECHO "@ICONV_CONST@->"
SET SRC=%DST%
SET OLD=@ICONV_CONST@
SET NEW=
FOR /F "TOKENS=*" %%S IN (%SRC%) DO (
	SET TMP=%%S
	IF NOT !TMP!.==. (
	  SET TMP=!TMP:%OLD%=%NEW%!
	  @ECHO !TMP!>>TMP.TMP
	)
)
MOVE TMP.TMP %DST%

@ECHO "@USE_MBSTATE_T@->0"
SET SRC=%DST%
SET OLD=@USE_MBSTATE_T@
SET NEW=0
FOR /F "TOKENS=*" %%S IN (%SRC%) DO (
	SET TMP=%%S
	IF NOT !TMP!.==. (
	  SET TMP=!TMP:%OLD%=%NEW%!
	  @ECHO !TMP!>>TMP.TMP
	)
)
MOVE TMP.TMP %DST%

@ECHO "@HAVE_WCHAR_T@->0"
SET SRC=%DST%
SET OLD=@HAVE_WCHAR_T@
SET NEW=0
FOR /F "TOKENS=*" %%S IN (%SRC%) DO (
	SET TMP=%%S
	IF NOT !TMP!.==. (
	  SET TMP=!TMP:%OLD%=%NEW%!
	  @ECHO !TMP!>>TMP.TMP
	)
)
MOVE TMP.TMP %DST%

CHCP 936